config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :flats do
    collection { post :import }
  end

  resources :dashboard
  root to: "home#index"
  

end

app/models/flat.rb
require 'csv'

class Flat < ActiveRecord::Base
  def self.import(file)
    CSV.foreach(file.path, :encoding => 'windows-1251:utf-8', headers: true) do |row|
      flat = find_by_id(row["id"]) || new
      flat.attributes = row.to_hash
      flat.save!
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!
  
  def index
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  # GET /flats
  # GET /flats.json
  def index
    @flats = Flat.all
  end

  # GET /flats/1
  # GET /flats/1.json
  def show
  end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  # GET /flats/1/edit
  def edit
  end

  # POST /flats
  # POST /flats.json
  def create
    @flat = Flat.new(flat_params)

    respond_to do |format|
      if @flat.save
        format.html { redirect_to @flat, notice: 'Flat was successfully created.' }
        format.json { render :show, status: :created, location: @flat }
      else
        format.html { render :new }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flats/1
  # PATCH/PUT /flats/1.json
  def update
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to @flat, notice: 'Flat was successfully updated.' }
        format.json { render :show, status: :ok, location: @flat }
      else
        format.html { render :edit }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flats/1
  # DELETE /flats/1.json
  def destroy
    @flat.destroy
    respond_to do |format|
      format.html { redirect_to flats_url, notice: 'Flat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Flat.import(params[:file])
    redirect_to flats_path, notice: "Flats Information Added Successfully"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flat_params
      params.require(:flat).permit(:block, :floor, :flat)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to :controller=>'dashboard', :action => 'index'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/dashboard/index.html.erb
<h1>Welcome to our dashboard</h1>

app/views/flats/_form.html.erb
<%= form_for(@flat) do |f| %>
  <% if @flat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flat.errors.count, "error") %> prohibited this flat from being saved:</h2>

      <ul>
      <% @flat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :block %><br>
    <%= f.text_field :block %>
  </div>
  <div class="field">
    <%= f.label :floor %><br>
    <%= f.text_field :floor %>
  </div>
  <div class="field">
    <%= f.label :flat %><br>
    <%= f.text_field :flat %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<h1>Editing Flat</h1>

<%= render 'form' %>

<%= link_to 'Show', @flat %> |
<%= link_to 'Back', flats_path %>

app/views/flats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Flats</h1>

<table>
  <thead>
    <tr>
      <th>Block</th>
      <th>Floor</th>
      <th>Flat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flats.each do |flat| %>
      <tr>
        <td><%= flat.block %></td>
        <td><%= flat.floor %></td>
        <td><%= flat.flat %></td>
        <td><%= link_to 'Show', flat %></td>
        <td><%= link_to 'Edit', edit_flat_path(flat) %></td>
        <td><%= link_to 'Destroy', flat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flat', new_flat_path %>

<br>

<h3>Import Flats</h3>
<%= form_tag import_flats_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload Flats" %>
<% end %>

app/views/flats/new.html.erb
<h1>New Flat</h1>

<%= render 'form' %>

<%= link_to 'Back', flats_path %>

app/views/flats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Block:</strong>
  <%= @flat.block %>
</p>

<p>
  <strong>Floor:</strong>
  <%= @flat.floor %>
</p>

<p>
  <strong>Flat:</strong>
  <%= @flat.flat %>
</p>

<%= link_to 'Edit', edit_flat_path(@flat) %> |
<%= link_to 'Back', flats_path %>

app/views/home/index.html.erb
<h1> Welcome to our Website </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Estate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign Up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path  %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<%= yield %>

</body>
</html>